
package com.advancia.wsImport2.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IdCardServiceImpl", targetNamespace = "http://service.idCardSoap.advancia.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IdCardServiceImpl {


    /**
     * 
     * @return
     *     returns java.util.List<com.advancia.wsImport2.ws.client.IdCard>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIdCardList", targetNamespace = "http://service.idCardSoap.advancia.com/", className = "com.advancia.wsImport2.ws.client.GetIdCardList")
    @ResponseWrapper(localName = "getIdCardListResponse", targetNamespace = "http://service.idCardSoap.advancia.com/", className = "com.advancia.wsImport2.ws.client.GetIdCardListResponse")
    @Action(input = "http://service.idCardSoap.advancia.com/IdCardServiceImpl/getIdCardListRequest", output = "http://service.idCardSoap.advancia.com/IdCardServiceImpl/getIdCardListResponse")
    public List<IdCard> getIdCardList();

}
